[build]
publish = "dist"
command = "BASE_URL=$DEPLOY_URL pnpm i --shamefully-hoist && pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200  